name: Django CI

on :
  push :
    branches: ["main"]
  pull_request :
    branches: ["main"]
  
jobs :
  build :

    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps :
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with :
        python-version: 3.x

    - name: Create Vritual Environment
      run: python3 -m venv venv

    - name: Activate Vritual Environment
      run: source venv/bin/activate

    - name: Install reqiurements
      run: pip install -r requirements.txt

    - name: Run Test cases
      run: python3 manage.py test